<?php
/******************************************************************************
 * NINA VIỆT NAM
 * Email: nina@nina.vn
 * Website: nina.vn
 * Version: 1.1.1 
 * Date 18-09-2024
 * Đây là tài sản của CÔNG TY TNHH TM DV NINA. Vui lòng không sử dụng khi chưa được phép.
 */

return [
    'logo' => [
        'title_main' => "Logo",
        'kind' => 'static',
        'title' => true,
        'desc' => false,
        'desc_cke' => false,
        'link' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 108,
        'height' => 66,
        'thumb' => '108x66x1',
    ],
    'logoft' => [
        'title_main' => "Logo footer",
        'kind' => 'static',
        'title' => true,
        'desc' => true,
        'desc_cke' => false,
        'link' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 176,
        'height' => 176,
        'thumb' => '176x176x1',
    ],
    'banner' => [
        'title_main' => "Banner",
        'kind' => 'static',
        'title' => true,
        'desc' => false,
        'desc_cke' => false,
        'link' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 363,
        'height' => 92,
        'thumb' => '363x92x1',
    ],
    'img-tc' => [
        'title_main' => "Hình tiêu chí",
        'kind' => 'static',
        'title' => true,
        'desc' => false,
        'desc_cke' => false,
        'link' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 450,
        'height' => 450,
        'thumb' => '450x450x1',
    ],
    'qc' => [
        'title_main' => "Banner quảng cáo",
        'kind' => 'static',
        'desc' => false,
        'desc_cke' => false,
        'link' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 1366,
        'height' => 360,
        'thumb' => '1366x360x1',
    ],
    'favicon' => [
        'title_main' => "Favicon",
        'kind' => 'static',
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 48,
        'height' => 48,
        'thumb' => '48x48x1',
    ],
    'slide' => [
        'title_main' => "Slideshow",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'desc_cke' => false,
        'width' => 1366,
        'height' => 560,
        'thumb' => '1366x560x1',
    ],
    'social' => [
        'title_main' => "Mạng xã hội",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 37,
        'height' => 37,
        'thumb' => '37x37x2',
    ],
    'doi-tac' => [
        'title_main' => "Đối tác",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 190,
        'height' => 130,
        'thumb' => '190x130x2',
    ],
    'watermark_product' => [
        'title_main' => "Con dấu sản phẩm",
        'kind' => 'static',
        'watermark' =>true,
        'desc' => false,
        'title' => false,
        'desc_cke' => false,
        'link' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 70,
        'height' => 70,
        'thumb' => '70x70x1',
    ]
];